import page from "../node_modules/page/page.mjs";
import { session, updateNav } from "./utils.js";
import { showCreate } from "./views/create.js";
import { showDashboard } from "./views/dashboard.js";
import { showDetails } from "./views/details.js";
import { showEdit } from "./views/edit.js";
import { showHome } from "./views/home.js";
import { showLogin } from "./views/login.js";
import { showRegister } from "./views/register.js";
import { showSearch } from "./views/search.js";

page(session);
page(updateNav);
page("/", showHome);
page("/login", showLogin);
page("/register", showRegister);
page("/dashboard", showDashboard);
page("/details/:id", showDetails);
page("/create", showCreate);
page("/edit/:id", showEdit);
page("/search", showSearch);
page.start();
